// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cordiccart2pol_cordiccart2pol_Pipeline_cordic_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        select_ln1697,
        select_ln1697_1,
        x_cordic_V_5_out,
        x_cordic_V_5_out_ap_vld,
        theta_out_V_out,
        theta_out_V_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [14:0] select_ln1697;
input  [14:0] select_ln1697_1;
output  [14:0] x_cordic_V_5_out;
output   x_cordic_V_5_out_ap_vld;
output  [14:0] theta_out_V_out;
output   theta_out_V_out_ap_vld;

reg ap_idle;
reg x_cordic_V_5_out_ap_vld;
reg theta_out_V_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln28_fu_412_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] i_1_load_fu_389_p1;
wire   [0:0] tmp_2_fu_429_p3;
reg   [0:0] tmp_2_reg_1008;
wire   [14:0] y_cordic_V_4_fu_641_p2;
reg   [14:0] y_cordic_V_4_reg_1012;
wire   [14:0] x_cordic_V_1_fu_647_p2;
reg   [14:0] x_cordic_V_1_reg_1017;
wire   [14:0] y_cordic_V_3_fu_892_p2;
reg   [14:0] y_cordic_V_3_reg_1022;
wire   [14:0] x_cordic_V_fu_898_p2;
reg   [14:0] x_cordic_V_reg_1027;
reg   [13:0] ap_phi_mux_r_22_pn_phi_fu_171_p22;
wire   [13:0] zext_ln1534_fu_627_p1;
wire   [13:0] ap_phi_reg_pp0_iter1_r_22_pn_reg_168;
wire   [13:0] zext_ln1534_9_fu_447_p1;
wire   [13:0] zext_ln1534_8_fu_467_p1;
wire   [13:0] zext_ln1534_7_fu_487_p1;
wire   [13:0] zext_ln1534_6_fu_507_p1;
wire   [13:0] zext_ln1534_5_fu_527_p1;
wire   [13:0] zext_ln1534_4_fu_547_p1;
wire   [13:0] zext_ln1534_3_fu_567_p1;
wire   [13:0] zext_ln1534_2_fu_587_p1;
wire   [13:0] zext_ln1534_1_fu_607_p1;
wire   [13:0] trunc_ln28_fu_424_p1;
reg   [14:0] ap_phi_mux_r_23_pn_phi_fu_198_p22;
wire  signed [14:0] sext_ln1534_4_fu_632_p1;
wire   [14:0] ap_phi_reg_pp0_iter1_r_23_pn_reg_195;
wire  signed [14:0] sext_ln1534_13_fu_452_p1;
wire  signed [14:0] sext_ln1534_12_fu_472_p1;
wire  signed [14:0] sext_ln1534_11_fu_492_p1;
wire  signed [14:0] sext_ln1534_10_fu_512_p1;
wire  signed [14:0] sext_ln1534_9_fu_532_p1;
wire  signed [14:0] sext_ln1534_8_fu_552_p1;
wire  signed [14:0] sext_ln1534_7_fu_572_p1;
wire  signed [14:0] sext_ln1534_6_fu_592_p1;
wire  signed [14:0] sext_ln1534_5_fu_612_p1;
reg   [14:0] ap_phi_mux_r_42_pn_phi_fu_225_p22;
wire  signed [14:0] sext_ln1534_fu_882_p1;
wire   [14:0] ap_phi_reg_pp0_iter1_r_42_pn_reg_222;
wire  signed [14:0] sext_ln1534_28_fu_702_p1;
wire  signed [14:0] sext_ln1534_26_fu_722_p1;
wire  signed [14:0] sext_ln1534_24_fu_742_p1;
wire  signed [14:0] sext_ln1534_22_fu_762_p1;
wire  signed [14:0] sext_ln1534_20_fu_782_p1;
wire  signed [14:0] sext_ln1534_18_fu_802_p1;
wire  signed [14:0] sext_ln1534_16_fu_822_p1;
wire  signed [14:0] sext_ln1534_14_fu_842_p1;
wire  signed [14:0] sext_ln1534_2_fu_862_p1;
reg   [14:0] ap_phi_mux_r_25_pn_phi_fu_252_p22;
wire  signed [14:0] sext_ln1534_1_fu_887_p1;
wire   [14:0] ap_phi_reg_pp0_iter1_r_25_pn_reg_249;
wire  signed [14:0] sext_ln1534_29_fu_707_p1;
wire  signed [14:0] sext_ln1534_27_fu_727_p1;
wire  signed [14:0] sext_ln1534_25_fu_747_p1;
wire  signed [14:0] sext_ln1534_23_fu_767_p1;
wire  signed [14:0] sext_ln1534_21_fu_787_p1;
wire  signed [14:0] sext_ln1534_19_fu_807_p1;
wire  signed [14:0] sext_ln1534_17_fu_827_p1;
wire  signed [14:0] sext_ln1534_15_fu_847_p1;
wire  signed [14:0] sext_ln1534_3_fu_867_p1;
reg   [14:0] theta_out_V_fu_126;
wire   [14:0] theta_out_V_3_fu_681_p2;
wire   [14:0] theta_out_V_2_fu_932_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [3:0] i_fu_130;
wire   [3:0] add_ln28_fu_418_p2;
reg   [14:0] x_temp_V_fu_134;
reg   [14:0] ap_sig_allocacmp_x_cordic_V_2;
reg   [14:0] y_cordic_V_fu_138;
reg   [14:0] ap_sig_allocacmp_y_cordic_V_1;
wire    ap_block_pp0_stage0_01001;
wire   [4:0] r_21_fu_437_p4;
wire   [5:0] grp_fu_276_p4;
wire   [5:0] r_19_fu_457_p4;
wire   [6:0] grp_fu_285_p4;
wire   [6:0] r_17_fu_477_p4;
wire   [7:0] grp_fu_294_p4;
wire   [7:0] r_15_fu_497_p4;
wire   [8:0] grp_fu_303_p4;
wire   [8:0] r_13_fu_517_p4;
wire   [9:0] grp_fu_312_p4;
wire   [9:0] r_11_fu_537_p4;
wire   [10:0] grp_fu_321_p4;
wire   [10:0] r_39_fu_557_p4;
wire   [11:0] grp_fu_330_p4;
wire   [11:0] r_8_fu_577_p4;
wire   [12:0] grp_fu_339_p4;
wire   [12:0] r_6_fu_597_p4;
wire   [13:0] grp_fu_348_p4;
wire   [3:0] r_4_fu_617_p4;
wire   [4:0] grp_fu_357_p4;
wire   [14:0] zext_ln12_fu_637_p1;
wire   [14:0] tmp_fu_653_p13;
wire   [5:0] r_37_fu_692_p4;
wire   [6:0] r_35_fu_712_p4;
wire   [7:0] r_33_fu_732_p4;
wire   [8:0] r_31_fu_752_p4;
wire   [9:0] r_29_fu_772_p4;
wire   [10:0] r_27_fu_792_p4;
wire   [11:0] r_25_fu_812_p4;
wire   [12:0] r_23_fu_832_p4;
wire   [13:0] r_2_fu_852_p4;
wire   [4:0] r_fu_872_p4;
wire   [14:0] tmp_1_fu_904_p13;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_689;
reg    ap_condition_693;
reg    ap_condition_696;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

cordiccart2pol_mux_114_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 15 ),
    .din5_WIDTH( 15 ),
    .din6_WIDTH( 15 ),
    .din7_WIDTH( 15 ),
    .din8_WIDTH( 15 ),
    .din9_WIDTH( 15 ),
    .din10_WIDTH( 15 ),
    .din11_WIDTH( 4 ),
    .dout_WIDTH( 15 ))
mux_114_15_1_1_U1(
    .din0(15'd3217),
    .din1(15'd1899),
    .din2(15'd1003),
    .din3(15'd509),
    .din4(15'd256),
    .din5(15'd128),
    .din6(15'd64),
    .din7(15'd32),
    .din8(15'd16),
    .din9(15'd8),
    .din10(15'd4),
    .din11(i_fu_130),
    .dout(tmp_fu_653_p13)
);

cordiccart2pol_mux_114_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 15 ),
    .din5_WIDTH( 15 ),
    .din6_WIDTH( 15 ),
    .din7_WIDTH( 15 ),
    .din8_WIDTH( 15 ),
    .din9_WIDTH( 15 ),
    .din10_WIDTH( 15 ),
    .din11_WIDTH( 4 ),
    .dout_WIDTH( 15 ))
mux_114_15_1_1_U2(
    .din0(15'd3217),
    .din1(15'd1899),
    .din2(15'd1003),
    .din3(15'd509),
    .din4(15'd256),
    .din5(15'd128),
    .din6(15'd64),
    .din7(15'd32),
    .din8(15'd16),
    .din9(15'd8),
    .din10(15'd4),
    .din11(i_fu_130),
    .dout(tmp_1_fu_904_p13)
);

cordiccart2pol_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_130 <= 4'd0;
        end else if (((icmp_ln28_fu_412_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_130 <= add_ln28_fu_418_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            theta_out_V_fu_126 <= 15'd0;
        end else if ((1'b1 == ap_condition_696)) begin
            theta_out_V_fu_126 <= theta_out_V_2_fu_932_p2;
        end else if ((1'b1 == ap_condition_693)) begin
            theta_out_V_fu_126 <= theta_out_V_3_fu_681_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            x_temp_V_fu_134 <= select_ln1697;
        end else if (((tmp_2_reg_1008 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            x_temp_V_fu_134 <= x_cordic_V_reg_1027;
        end else if (((tmp_2_reg_1008 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            x_temp_V_fu_134 <= x_cordic_V_1_reg_1017;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            y_cordic_V_fu_138 <= select_ln1697_1;
        end else if (((tmp_2_reg_1008 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            y_cordic_V_fu_138 <= y_cordic_V_3_reg_1022;
        end else if (((tmp_2_reg_1008 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            y_cordic_V_fu_138 <= y_cordic_V_4_reg_1012;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln28_fu_412_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_2_reg_1008 <= ap_sig_allocacmp_y_cordic_V_1[32'd14];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_429_p3 == 1'd0) & (icmp_ln28_fu_412_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_cordic_V_1_reg_1017 <= x_cordic_V_1_fu_647_p2;
        y_cordic_V_4_reg_1012 <= y_cordic_V_4_fu_641_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_429_p3 == 1'd1) & (icmp_ln28_fu_412_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_cordic_V_reg_1027 <= x_cordic_V_fu_898_p2;
        y_cordic_V_3_reg_1022 <= y_cordic_V_3_fu_892_p2;
    end
end

always @ (*) begin
    if (((icmp_ln28_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_fu_429_p3 == 1'd0) & (icmp_ln28_fu_412_p2 == 1'd0))) begin
        if ((1'b1 == ap_condition_689)) begin
            ap_phi_mux_r_22_pn_phi_fu_171_p22 = trunc_ln28_fu_424_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd1)) begin
            ap_phi_mux_r_22_pn_phi_fu_171_p22 = zext_ln1534_1_fu_607_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd2)) begin
            ap_phi_mux_r_22_pn_phi_fu_171_p22 = zext_ln1534_2_fu_587_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd3)) begin
            ap_phi_mux_r_22_pn_phi_fu_171_p22 = zext_ln1534_3_fu_567_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd4)) begin
            ap_phi_mux_r_22_pn_phi_fu_171_p22 = zext_ln1534_4_fu_547_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd5)) begin
            ap_phi_mux_r_22_pn_phi_fu_171_p22 = zext_ln1534_5_fu_527_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd6)) begin
            ap_phi_mux_r_22_pn_phi_fu_171_p22 = zext_ln1534_6_fu_507_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd7)) begin
            ap_phi_mux_r_22_pn_phi_fu_171_p22 = zext_ln1534_7_fu_487_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd8)) begin
            ap_phi_mux_r_22_pn_phi_fu_171_p22 = zext_ln1534_8_fu_467_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd9)) begin
            ap_phi_mux_r_22_pn_phi_fu_171_p22 = zext_ln1534_9_fu_447_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd10)) begin
            ap_phi_mux_r_22_pn_phi_fu_171_p22 = zext_ln1534_fu_627_p1;
        end else begin
            ap_phi_mux_r_22_pn_phi_fu_171_p22 = ap_phi_reg_pp0_iter1_r_22_pn_reg_168;
        end
    end else begin
        ap_phi_mux_r_22_pn_phi_fu_171_p22 = ap_phi_reg_pp0_iter1_r_22_pn_reg_168;
    end
end

always @ (*) begin
    if (((tmp_2_fu_429_p3 == 1'd0) & (icmp_ln28_fu_412_p2 == 1'd0))) begin
        if ((1'b1 == ap_condition_689)) begin
            ap_phi_mux_r_23_pn_phi_fu_198_p22 = ap_sig_allocacmp_x_cordic_V_2;
        end else if ((i_1_load_fu_389_p1 == 4'd1)) begin
            ap_phi_mux_r_23_pn_phi_fu_198_p22 = sext_ln1534_5_fu_612_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd2)) begin
            ap_phi_mux_r_23_pn_phi_fu_198_p22 = sext_ln1534_6_fu_592_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd3)) begin
            ap_phi_mux_r_23_pn_phi_fu_198_p22 = sext_ln1534_7_fu_572_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd4)) begin
            ap_phi_mux_r_23_pn_phi_fu_198_p22 = sext_ln1534_8_fu_552_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd5)) begin
            ap_phi_mux_r_23_pn_phi_fu_198_p22 = sext_ln1534_9_fu_532_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd6)) begin
            ap_phi_mux_r_23_pn_phi_fu_198_p22 = sext_ln1534_10_fu_512_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd7)) begin
            ap_phi_mux_r_23_pn_phi_fu_198_p22 = sext_ln1534_11_fu_492_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd8)) begin
            ap_phi_mux_r_23_pn_phi_fu_198_p22 = sext_ln1534_12_fu_472_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd9)) begin
            ap_phi_mux_r_23_pn_phi_fu_198_p22 = sext_ln1534_13_fu_452_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd10)) begin
            ap_phi_mux_r_23_pn_phi_fu_198_p22 = sext_ln1534_4_fu_632_p1;
        end else begin
            ap_phi_mux_r_23_pn_phi_fu_198_p22 = ap_phi_reg_pp0_iter1_r_23_pn_reg_195;
        end
    end else begin
        ap_phi_mux_r_23_pn_phi_fu_198_p22 = ap_phi_reg_pp0_iter1_r_23_pn_reg_195;
    end
end

always @ (*) begin
    if (((tmp_2_fu_429_p3 == 1'd1) & (icmp_ln28_fu_412_p2 == 1'd0))) begin
        if ((1'b1 == ap_condition_689)) begin
            ap_phi_mux_r_25_pn_phi_fu_252_p22 = ap_sig_allocacmp_x_cordic_V_2;
        end else if ((i_1_load_fu_389_p1 == 4'd1)) begin
            ap_phi_mux_r_25_pn_phi_fu_252_p22 = sext_ln1534_3_fu_867_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd2)) begin
            ap_phi_mux_r_25_pn_phi_fu_252_p22 = sext_ln1534_15_fu_847_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd3)) begin
            ap_phi_mux_r_25_pn_phi_fu_252_p22 = sext_ln1534_17_fu_827_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd4)) begin
            ap_phi_mux_r_25_pn_phi_fu_252_p22 = sext_ln1534_19_fu_807_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd5)) begin
            ap_phi_mux_r_25_pn_phi_fu_252_p22 = sext_ln1534_21_fu_787_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd6)) begin
            ap_phi_mux_r_25_pn_phi_fu_252_p22 = sext_ln1534_23_fu_767_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd7)) begin
            ap_phi_mux_r_25_pn_phi_fu_252_p22 = sext_ln1534_25_fu_747_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd8)) begin
            ap_phi_mux_r_25_pn_phi_fu_252_p22 = sext_ln1534_27_fu_727_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd9)) begin
            ap_phi_mux_r_25_pn_phi_fu_252_p22 = sext_ln1534_29_fu_707_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd10)) begin
            ap_phi_mux_r_25_pn_phi_fu_252_p22 = sext_ln1534_1_fu_887_p1;
        end else begin
            ap_phi_mux_r_25_pn_phi_fu_252_p22 = ap_phi_reg_pp0_iter1_r_25_pn_reg_249;
        end
    end else begin
        ap_phi_mux_r_25_pn_phi_fu_252_p22 = ap_phi_reg_pp0_iter1_r_25_pn_reg_249;
    end
end

always @ (*) begin
    if (((tmp_2_fu_429_p3 == 1'd1) & (icmp_ln28_fu_412_p2 == 1'd0))) begin
        if ((1'b1 == ap_condition_689)) begin
            ap_phi_mux_r_42_pn_phi_fu_225_p22 = ap_sig_allocacmp_y_cordic_V_1;
        end else if ((i_1_load_fu_389_p1 == 4'd1)) begin
            ap_phi_mux_r_42_pn_phi_fu_225_p22 = sext_ln1534_2_fu_862_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd2)) begin
            ap_phi_mux_r_42_pn_phi_fu_225_p22 = sext_ln1534_14_fu_842_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd3)) begin
            ap_phi_mux_r_42_pn_phi_fu_225_p22 = sext_ln1534_16_fu_822_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd4)) begin
            ap_phi_mux_r_42_pn_phi_fu_225_p22 = sext_ln1534_18_fu_802_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd5)) begin
            ap_phi_mux_r_42_pn_phi_fu_225_p22 = sext_ln1534_20_fu_782_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd6)) begin
            ap_phi_mux_r_42_pn_phi_fu_225_p22 = sext_ln1534_22_fu_762_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd7)) begin
            ap_phi_mux_r_42_pn_phi_fu_225_p22 = sext_ln1534_24_fu_742_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd8)) begin
            ap_phi_mux_r_42_pn_phi_fu_225_p22 = sext_ln1534_26_fu_722_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd9)) begin
            ap_phi_mux_r_42_pn_phi_fu_225_p22 = sext_ln1534_28_fu_702_p1;
        end else if ((i_1_load_fu_389_p1 == 4'd10)) begin
            ap_phi_mux_r_42_pn_phi_fu_225_p22 = sext_ln1534_fu_882_p1;
        end else begin
            ap_phi_mux_r_42_pn_phi_fu_225_p22 = ap_phi_reg_pp0_iter1_r_42_pn_reg_222;
        end
    end else begin
        ap_phi_mux_r_42_pn_phi_fu_225_p22 = ap_phi_reg_pp0_iter1_r_42_pn_reg_222;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((tmp_2_reg_1008 == 1'd1)) begin
            ap_sig_allocacmp_x_cordic_V_2 = x_cordic_V_reg_1027;
        end else if ((tmp_2_reg_1008 == 1'd0)) begin
            ap_sig_allocacmp_x_cordic_V_2 = x_cordic_V_1_reg_1017;
        end else begin
            ap_sig_allocacmp_x_cordic_V_2 = x_temp_V_fu_134;
        end
    end else begin
        ap_sig_allocacmp_x_cordic_V_2 = x_temp_V_fu_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((tmp_2_reg_1008 == 1'd1)) begin
            ap_sig_allocacmp_y_cordic_V_1 = y_cordic_V_3_reg_1022;
        end else if ((tmp_2_reg_1008 == 1'd0)) begin
            ap_sig_allocacmp_y_cordic_V_1 = y_cordic_V_4_reg_1012;
        end else begin
            ap_sig_allocacmp_y_cordic_V_1 = y_cordic_V_fu_138;
        end
    end else begin
        ap_sig_allocacmp_y_cordic_V_1 = y_cordic_V_fu_138;
    end
end

always @ (*) begin
    if (((icmp_ln28_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        theta_out_V_out_ap_vld = 1'b1;
    end else begin
        theta_out_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln28_fu_412_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_cordic_V_5_out_ap_vld = 1'b1;
    end else begin
        x_cordic_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln28_fu_418_p2 = (i_fu_130 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_689 = (~(i_1_load_fu_389_p1 == 4'd1) & ~(i_1_load_fu_389_p1 == 4'd2) & ~(i_1_load_fu_389_p1 == 4'd3) & ~(i_1_load_fu_389_p1 == 4'd4) & ~(i_1_load_fu_389_p1 == 4'd5) & ~(i_1_load_fu_389_p1 == 4'd6) & ~(i_1_load_fu_389_p1 == 4'd7) & ~(i_1_load_fu_389_p1 == 4'd8) & ~(i_1_load_fu_389_p1 == 4'd9) & ~(i_1_load_fu_389_p1 == 4'd10));
end

always @ (*) begin
    ap_condition_693 = ((tmp_2_fu_429_p3 == 1'd0) & (icmp_ln28_fu_412_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_696 = ((tmp_2_fu_429_p3 == 1'd1) & (icmp_ln28_fu_412_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter1_r_22_pn_reg_168 = 'bx;

assign ap_phi_reg_pp0_iter1_r_23_pn_reg_195 = 'bx;

assign ap_phi_reg_pp0_iter1_r_25_pn_reg_249 = 'bx;

assign ap_phi_reg_pp0_iter1_r_42_pn_reg_222 = 'bx;

assign grp_fu_276_p4 = {{ap_sig_allocacmp_x_cordic_V_2[14:9]}};

assign grp_fu_285_p4 = {{ap_sig_allocacmp_x_cordic_V_2[14:8]}};

assign grp_fu_294_p4 = {{ap_sig_allocacmp_x_cordic_V_2[14:7]}};

assign grp_fu_303_p4 = {{ap_sig_allocacmp_x_cordic_V_2[14:6]}};

assign grp_fu_312_p4 = {{ap_sig_allocacmp_x_cordic_V_2[14:5]}};

assign grp_fu_321_p4 = {{ap_sig_allocacmp_x_cordic_V_2[14:4]}};

assign grp_fu_330_p4 = {{ap_sig_allocacmp_x_cordic_V_2[14:3]}};

assign grp_fu_339_p4 = {{ap_sig_allocacmp_x_cordic_V_2[14:2]}};

assign grp_fu_348_p4 = {{ap_sig_allocacmp_x_cordic_V_2[14:1]}};

assign grp_fu_357_p4 = {{ap_sig_allocacmp_x_cordic_V_2[14:10]}};

assign i_1_load_fu_389_p1 = i_fu_130;

assign icmp_ln28_fu_412_p2 = ((i_fu_130 == 4'd11) ? 1'b1 : 1'b0);

assign r_11_fu_537_p4 = {{ap_sig_allocacmp_y_cordic_V_1[13:4]}};

assign r_13_fu_517_p4 = {{ap_sig_allocacmp_y_cordic_V_1[13:5]}};

assign r_15_fu_497_p4 = {{ap_sig_allocacmp_y_cordic_V_1[13:6]}};

assign r_17_fu_477_p4 = {{ap_sig_allocacmp_y_cordic_V_1[13:7]}};

assign r_19_fu_457_p4 = {{ap_sig_allocacmp_y_cordic_V_1[13:8]}};

assign r_21_fu_437_p4 = {{ap_sig_allocacmp_y_cordic_V_1[13:9]}};

assign r_23_fu_832_p4 = {{ap_sig_allocacmp_y_cordic_V_1[14:2]}};

assign r_25_fu_812_p4 = {{ap_sig_allocacmp_y_cordic_V_1[14:3]}};

assign r_27_fu_792_p4 = {{ap_sig_allocacmp_y_cordic_V_1[14:4]}};

assign r_29_fu_772_p4 = {{ap_sig_allocacmp_y_cordic_V_1[14:5]}};

assign r_2_fu_852_p4 = {{ap_sig_allocacmp_y_cordic_V_1[14:1]}};

assign r_31_fu_752_p4 = {{ap_sig_allocacmp_y_cordic_V_1[14:6]}};

assign r_33_fu_732_p4 = {{ap_sig_allocacmp_y_cordic_V_1[14:7]}};

assign r_35_fu_712_p4 = {{ap_sig_allocacmp_y_cordic_V_1[14:8]}};

assign r_37_fu_692_p4 = {{ap_sig_allocacmp_y_cordic_V_1[14:9]}};

assign r_39_fu_557_p4 = {{ap_sig_allocacmp_y_cordic_V_1[13:3]}};

assign r_4_fu_617_p4 = {{ap_sig_allocacmp_y_cordic_V_1[13:10]}};

assign r_6_fu_597_p4 = {{ap_sig_allocacmp_y_cordic_V_1[13:1]}};

assign r_8_fu_577_p4 = {{ap_sig_allocacmp_y_cordic_V_1[13:2]}};

assign r_fu_872_p4 = {{ap_sig_allocacmp_y_cordic_V_1[14:10]}};

assign sext_ln1534_10_fu_512_p1 = $signed(grp_fu_303_p4);

assign sext_ln1534_11_fu_492_p1 = $signed(grp_fu_294_p4);

assign sext_ln1534_12_fu_472_p1 = $signed(grp_fu_285_p4);

assign sext_ln1534_13_fu_452_p1 = $signed(grp_fu_276_p4);

assign sext_ln1534_14_fu_842_p1 = $signed(r_23_fu_832_p4);

assign sext_ln1534_15_fu_847_p1 = $signed(grp_fu_339_p4);

assign sext_ln1534_16_fu_822_p1 = $signed(r_25_fu_812_p4);

assign sext_ln1534_17_fu_827_p1 = $signed(grp_fu_330_p4);

assign sext_ln1534_18_fu_802_p1 = $signed(r_27_fu_792_p4);

assign sext_ln1534_19_fu_807_p1 = $signed(grp_fu_321_p4);

assign sext_ln1534_1_fu_887_p1 = $signed(grp_fu_357_p4);

assign sext_ln1534_20_fu_782_p1 = $signed(r_29_fu_772_p4);

assign sext_ln1534_21_fu_787_p1 = $signed(grp_fu_312_p4);

assign sext_ln1534_22_fu_762_p1 = $signed(r_31_fu_752_p4);

assign sext_ln1534_23_fu_767_p1 = $signed(grp_fu_303_p4);

assign sext_ln1534_24_fu_742_p1 = $signed(r_33_fu_732_p4);

assign sext_ln1534_25_fu_747_p1 = $signed(grp_fu_294_p4);

assign sext_ln1534_26_fu_722_p1 = $signed(r_35_fu_712_p4);

assign sext_ln1534_27_fu_727_p1 = $signed(grp_fu_285_p4);

assign sext_ln1534_28_fu_702_p1 = $signed(r_37_fu_692_p4);

assign sext_ln1534_29_fu_707_p1 = $signed(grp_fu_276_p4);

assign sext_ln1534_2_fu_862_p1 = $signed(r_2_fu_852_p4);

assign sext_ln1534_3_fu_867_p1 = $signed(grp_fu_348_p4);

assign sext_ln1534_4_fu_632_p1 = $signed(grp_fu_357_p4);

assign sext_ln1534_5_fu_612_p1 = $signed(grp_fu_348_p4);

assign sext_ln1534_6_fu_592_p1 = $signed(grp_fu_339_p4);

assign sext_ln1534_7_fu_572_p1 = $signed(grp_fu_330_p4);

assign sext_ln1534_8_fu_552_p1 = $signed(grp_fu_321_p4);

assign sext_ln1534_9_fu_532_p1 = $signed(grp_fu_312_p4);

assign sext_ln1534_fu_882_p1 = $signed(r_fu_872_p4);

assign theta_out_V_2_fu_932_p2 = (theta_out_V_fu_126 - tmp_1_fu_904_p13);

assign theta_out_V_3_fu_681_p2 = (tmp_fu_653_p13 + theta_out_V_fu_126);

assign theta_out_V_out = theta_out_V_fu_126;

assign tmp_2_fu_429_p3 = ap_sig_allocacmp_y_cordic_V_1[32'd14];

assign trunc_ln28_fu_424_p1 = ap_sig_allocacmp_y_cordic_V_1[13:0];

assign x_cordic_V_1_fu_647_p2 = (zext_ln12_fu_637_p1 + ap_sig_allocacmp_x_cordic_V_2);

assign x_cordic_V_5_out = x_temp_V_fu_134;

assign x_cordic_V_fu_898_p2 = (ap_sig_allocacmp_x_cordic_V_2 - ap_phi_mux_r_42_pn_phi_fu_225_p22);

assign y_cordic_V_3_fu_892_p2 = (ap_sig_allocacmp_y_cordic_V_1 + ap_phi_mux_r_25_pn_phi_fu_252_p22);

assign y_cordic_V_4_fu_641_p2 = (ap_sig_allocacmp_y_cordic_V_1 - ap_phi_mux_r_23_pn_phi_fu_198_p22);

assign zext_ln12_fu_637_p1 = ap_phi_mux_r_22_pn_phi_fu_171_p22;

assign zext_ln1534_1_fu_607_p1 = r_6_fu_597_p4;

assign zext_ln1534_2_fu_587_p1 = r_8_fu_577_p4;

assign zext_ln1534_3_fu_567_p1 = r_39_fu_557_p4;

assign zext_ln1534_4_fu_547_p1 = r_11_fu_537_p4;

assign zext_ln1534_5_fu_527_p1 = r_13_fu_517_p4;

assign zext_ln1534_6_fu_507_p1 = r_15_fu_497_p4;

assign zext_ln1534_7_fu_487_p1 = r_17_fu_477_p4;

assign zext_ln1534_8_fu_467_p1 = r_19_fu_457_p4;

assign zext_ln1534_9_fu_447_p1 = r_21_fu_437_p4;

assign zext_ln1534_fu_627_p1 = r_4_fu_617_p4;

endmodule //cordiccart2pol_cordiccart2pol_Pipeline_cordic_loop
